-- CRIAR BD
CREATE DATABASE GREENHOUSE;

-- DEFINIR BD COMO PADRÃO / UTILIZÁVEL 
USE GREENHOUSE;

-- CRIAR TABELA / ENTIDADE 
CREATE TABLE `PLANTS` (
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VOLUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY `PK_PLANTS` (`PLANT_NAME`)
   
);